version: "3.9"

services:
    server:
      image: yuiarthur/linux_server
      networks:
        linux_backend:
      deploy:
        mode: replicated
        replicas: 3
      

    sql:
      image: mysql
      environment:
        MYSQL_DATABASE: smart_farm_db
        MYSQL_ROOT_PASSWORD: mysql
      networks:
        linux_backend:

    proxy:
      image: nginx
      networks:
        linux_backend:
      ports:
        - "80:80"
      volumes:
        - ./Nginx/view/dist:/usr/share/nginx/html
        - ./Nginx/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  linux_backendod:
    external: True